# Generated by Django 5.2.4 on 2025-08-06 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dni', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('age', models.IntegerField(default=18, verbose_name='Edad')),
                ('phone', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('position', models.CharField(max_length=50, verbose_name='Cargo')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitas/', verbose_name='Curriculum Vitae')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'erp_employee',
                'ordering': ['id'],
            },
        ),
    ]
