# Generated by Django 5.2.4 on 2025-08-13 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_client_product_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.category'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
